// api/token.js — EDGE runtime
export const config = { runtime: "edge" };

const textEncoder = new TextEncoder();

// base64url helper
const b64u = (buf) =>
  btoa(String.fromCharCode(...new Uint8Array(buf)))
    .replaceAll("+", "-")
    .replaceAll("/", "_")
    .replaceAll("=", "");

const b64uFromStr = (s) => {
  const bin = textEncoder.encode(s);
  let str = "";
  for (let i = 0; i < bin.length; i++) str += String.fromCharCode(bin[i]);
  return btoa(str).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", "");
};

// HMAC-SHA256
async function hs256Sign(secret, dataUint8) {
  const key = await crypto.subtle.importKey(
    "raw",
    textEncoder.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  return crypto.subtle.sign("HMAC", key, dataUint8);
}

// uuid v4 sederhana
function uuid4() {
  const a = crypto.getRandomValues(new Uint8Array(16));
  a[6] = (a[6] & 0x0f) | 0x40;
  a[8] = (a[8] & 0x3f) | 0x80;
  const h = [...a].map(x => x.toString(16).padStart(2, "0")).join("");
  return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;
}

function jsonResponse(obj, status = 200) {
  return new Response(JSON.stringify(obj), {
    status,
    headers: {
      "content-type": "application/json; charset=utf-8",
      "access-control-allow-origin": "*",
      "access-control-allow-methods": "GET,POST,OPTIONS",
      "access-control-allow-headers": "content-type, authorization",
      "cache-control": "no-store, no-cache, must-revalidate, max-age=0",
      pragma: "no-cache",
      expires: "0",
    },
  });
}

export default async function handler(req) {
  if (req.method === "OPTIONS") return new Response(null, { status: 204 });

  // langsung pakai secret fix
  const JWT_SECRET = "hR8%Zp@1Qx#sK7!vLm4nBt$2Dy&Wj9^CgUf0*Xh6oPi3rYe+Aq5vMz7wNl8RbT";
  const ACCESS_TTL = 900;
  const AUTHOR = "FAJRIAG - https://github.com/FAJRIAG";

  const { searchParams } = new URL(req.url);
  const userId = Number(searchParams.get("userId") || "292042932");
  const registerType = String(searchParams.get("registerType") || "TEMP");

  const header = { alg: "HS256", typ: "JWT" };
  const now = Math.floor(Date.now() / 1000);
  const payload = { registerType, userId, iat: now, exp: now + ACCESS_TTL };

  const headerB64 = b64uFromStr(JSON.stringify(header));
  const payloadB64 = b64uFromStr(JSON.stringify(payload));
  const signingInput = `${headerB64}.${payloadB64}`;
  const sigBuf = await hs256Sign(JWT_SECRET, textEncoder.encode(signingInput));
  const signatureB64 = b64u(sigBuf);

  const jwt = `${signingInput}.${signatureB64}`;
  const wrapped = btoa(jwt);
  const deviceid = uuid4();

  return jsonResponse({
    author: AUTHOR,
    token: wrapped,
    deviceid,
    info: "Token auto-generated by FAJRIAG's token generator",
  });
}
