// api/token.js
import jwt from "jsonwebtoken";
import { randomUUID } from "crypto";

export default function handler(req, res) {
  const {
    JWT_SECRET = "hR8%Zp@1Qx#sK7!vLm4nBt$2Dy&Wj9^CgUf0*Xh6oPi3rYe+Aq5vMz7wNl8RbT",
    ACCESS_TTL = "900", // detik
    AUTHOR = "FAJRI AG - https://github.com/FAJRIAG"
  } = process.env;

  const userId = Number(req.query.userId || 292042932);
  const registerType = req.query.registerType || "TEMP";
  const payload = { registerType, userId };

  try {
    // 1) buat JWT
    const token = jwt.sign(payload, JWT_SECRET, {
      algorithm: "HS256",
      expiresIn: Number(ACCESS_TTL),
    });

    // 2) bungkus base64 (supaya strukturnya sama)
    const wrapped = Buffer.from(token, "utf8").toString("base64");

    // 3) deviceid random (UUID)
    const deviceid = randomUUID();

    res.status(200).json({
      author: AUTHOR,
      token: wrapped,
      deviceid,
      info: "Token auto-generated by your own Vercel function"
    });
  } catch (e) {
    res.status(500).json({ ok: false, error: e.message });
  }
}
